name: CI/CD pipeline

on:
  push:
    branches: [staging, main]

jobs:
  verify-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4

      - name: setup environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: install deps
        run: npm ci

      - name: linting check
        run: npm run lint

      - name: test
        run: npm test

      - name: build
        run: npm run build

      - name: upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
          retention-days: 1

  docker-build-push:
    needs: verify-and-build
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4

      - name: get the artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist/

      - name: debug the artifacts content
        run: ls -la dist/

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ak0384221/${{github.event.repository.name}}
